version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./pdfs:/app/pdfs
      - ./salida:/app/salida
    depends_on:
      - grobid
    environment:
      - GROBID_HOST=http://grobid:8070

  grobid:
    image: lfoppiano/grobid:0.7.2
    ports:
      - "8070:8070"
